<a href="https://colab.research.google.com/github/SamanMansoor/Data-Science/blob/main/Stress.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
import seaborn as sns
import warnings
import os

In [107]:
# Load the Excel file into a DataFrame
df = pd.read_excel('/content/Final (Data Analysis).xlsx')

# iterate through each column in the DataFrame
for col in df.columns:
    if df[col].dtype == 'object':
        # convert categorical data to numeric using pandas' factorize method
        df[col] = pd.factorize(df[col])[0]


print(df.head())

   Gender  Area (Living)  Age in years  Province  Weight (KG)    \
0       0              0            18         0           55.0
1       0              0            18         0           55.0
2       0              0            18         0           55.0
3       1              0            18         0           55.0
4       1              0            18         0           55.0

   Height (Feet)  No. of siblings (Total number of sisters & Brothers)  \
0              0                                                  0
1              0                                                  0
2              0                                                  0
3              1                                                  0
4              1                                                  0

   Your Highest Qualification  Family Occupation  Providing care to  ...  \
0                           0                  0                  0  ...
1                           1                  1                  1  ...
2                           2                  1                  1  ...
3                           1                  0                  2  ...
4                           2                  2                  1  ...

   The communication between teaching staff and students is good  \
0                                                  0
1                                                  1
2                                                  0
3                                                  1
4                                                  1

   I find teaching staff helpful when asked questions   \
0                                                  0
1                                                  1
2                                                  0
3                                                  2
4                                                  0

   I manage to complete the requirements of the program without feeling unduly stressed  \
0                                                  0
1                                                  0
2                                                  0
3                                                  1
4                                                  0

   The amount of work we are expected to do is quite reasonable.  \
0                                                  0
1                                                  0
2                                                  0
3                                                  1
4                                                  2

   I feel a strong sense of belonging to my class group  \
0                                                  0
1                                                  0
2                                                  1
3                                                  2
4                                                  1

   I frequently work together with others in my classes  \
0                                                  0
1                                                  0
2                                                  1
3                                                  2
4                                                  1

   I have frequently discussed ideas from courses with other students out-of-class  \
0                                                  0
1                                                  1
2                                                  2
3                                                  3
4                                                  1

   I have found that discussing course material with other students outside classes has helped me to reach a better understanding of the material  \
0                                                  0
1                                                  0
2                                                  0
3                                                  1
4                                                  2

   I can see how courses fitted together to make a coherent program of study for my major  \
0                                                  0
1                                                  0
2                                                  0
3                                                  1
4                                                  0

   The program of study for my major was well integrated.
0                                                  0
1                                                  1
2                                                  1
3                                                  2
4                                                  1

[5 rows x 134 columns]

In [108]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11401 entries, 0 to 11400
Columns: 134 entries, Gender to The program of study for my major was well integrated.
dtypes: float64(1), int64(133)
memory usage: 11.7 MB
None

In [109]:
print(df.describe())

             Gender  Area (Living)  Age in years      Province  Weight (KG)    \
count  11401.000000   11401.000000  11401.000000  11401.000000   11401.000000
mean       0.501447       0.223489     22.317867      0.448031      60.801407
std        0.672142       0.416602      6.936049      1.242644      13.959759
min        0.000000       0.000000     10.000000      0.000000      16.000000
25%        0.000000       0.000000     19.000000      0.000000      50.000000
50%        0.000000       0.000000     20.000000      0.000000      60.000000
75%        1.000000       0.000000     23.000000      0.000000      69.000000
max       17.000000       1.000000     87.000000      6.000000     178.000000

       Height (Feet)  No. of siblings (Total number of sisters & Brothers)  \
count   11401.000000                                       11401.000000
mean       42.128498                                           3.916586
std        18.470998                                           1.832113
min         0.000000                                           0.000000
25%        34.000000                                           3.000000
50%        43.000000                                           4.000000
75%        56.000000                                           5.000000
max        86.000000                                          12.000000

       Your Highest Qualification  Family Occupation  Providing care to  ...  \
count                11401.000000       11401.000000       11401.000000  ...
mean                     1.156741           1.530129           2.316990  ...
std                      1.023620           1.418422           1.133168  ...
min                      0.000000           0.000000           0.000000  ...
25%                      1.000000           0.000000           2.000000  ...
50%                      1.000000           1.000000           3.000000  ...
75%                      1.000000           3.000000           3.000000  ...
max                      4.000000           4.000000           5.000000  ...

       The communication between teaching staff and students is good  \
count                                       11401.000000
mean                                            1.131831
std                                             1.160719
min                                             0.000000
25%                                             0.000000
50%                                             1.000000
75%                                             2.000000
max                                             4.000000

       I find teaching staff helpful when asked questions   \
count                                       11401.000000
mean                                            1.123936
std                                             1.189718
min                                             0.000000
25%                                             0.000000
50%                                             1.000000
75%                                             2.000000
max                                             4.000000

       I manage to complete the requirements of the program without feeling unduly stressed  \
count                                       11401.000000
mean                                            1.497062
std                                             1.250900
min                                             0.000000
25%                                             0.000000
50%                                             2.000000
75%                                             2.000000
max                                             4.000000

       The amount of work we are expected to do is quite reasonable.  \
count                                       11401.000000
mean                                            1.394527
std                                             1.269252
min                                             0.000000
25%                                             0.000000
50%                                             2.000000
75%                                             2.000000
max                                             4.000000

       I feel a strong sense of belonging to my class group  \
count                                       11401.000000
mean                                            1.118411
std                                             1.193776
min                                             0.000000
25%                                             0.000000
50%                                             1.000000
75%                                             2.000000
max                                             4.000000

       I frequently work together with others in my classes  \
count                                       11401.000000
mean                                            1.142181
std                                             1.185605
min                                             0.000000
25%                                             0.000000
50%                                             1.000000
75%                                             2.000000
max                                             4.000000

       I have frequently discussed ideas from courses with other students out-of-class  \
count                                       11401.000000
mean                                            1.666608
std                                             1.034314
min                                             0.000000
25%                                             1.000000
50%                                             2.000000
75%                                             2.000000
max                                             4.000000

       I have found that discussing course material with other students outside classes has helped me to reach a better understanding of the material  \
count                                       11401.000000
mean                                            1.389176
std                                             1.276791
min                                             0.000000
25%                                             0.000000
50%                                             2.000000
75%                                             2.000000
max                                             4.000000

       I can see how courses fitted together to make a coherent program of study for my major  \
count                                       11401.000000
mean                                            1.421016
std                                             1.222491
min                                             0.000000
25%                                             0.000000
50%                                             2.000000
75%                                             2.000000
max                                             4.000000

       The program of study for my major was well integrated.
count                                       11401.000000
mean                                            1.090694
std                                             1.229685
min                                             0.000000
25%                                             0.000000
50%                                             1.000000
75%                                             1.000000
max                                             4.000000

[8 rows x 134 columns]

In [110]:
print(df.shape)

(11401, 134)

In [111]:
df.isnull()

,Gender,Area (Living),Age in years,Province,Weight (KG),Height (Feet),No. of siblings (Total number of sisters & Brothers),Your Highest Qualification,Family Occupation,Providing care to,...,The communication between teaching staff and students is good,I find teaching staff helpful when asked questions,I manage to complete the requirements of the program without feeling unduly stressed,The amount of work we are expected to do is quite reasonable.,I feel a strong sense of belonging to my class group,I frequently work together with others in my classes,I have frequently discussed ideas from courses with other students out-of-class,I have found that discussing course material with other students outside classes has helped me to reach a better understanding of the material,I can see how courses fitted together to make a coherent program of study for my major,The program of study for my major was well integrated.
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11396,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11397,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11398,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11399,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11400,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [112]:
df.isnull().sum()

Gender                                                                                                                                            0
Area (Living)                                                                                                                                     0
Age in years                                                                                                                                      0
Province                                                                                                                                          0
Weight (KG)                                                                                                                                       0
                                                                                                                                                 ..
I frequently work together with others in my classes                                                                                              0
I have frequently discussed ideas from courses with other students out-of-class                                                                   0
I have found that discussing course material with other students outside classes has helped me to reach a better understanding of the material    0
I can see how courses fitted together to make a coherent program of study for my major                                                            0
The program of study for my major was well integrated.                                                                                            0
Length: 134, dtype: int64

In [113]:
df.dtypes

Gender                                                                                                                                              int64
Area (Living)                                                                                                                                       int64
Age in years                                                                                                                                        int64
Province                                                                                                                                            int64
Weight (KG)                                                                                                                                       float64
                                                                                                                                                   ...
I frequently work together with others in my classes                                                                                                int64
I have frequently discussed ideas from courses with other students out-of-class                                                                     int64
I have found that discussing course material with other students outside classes has helped me to reach a better understanding of the material      int64
I can see how courses fitted together to make a coherent program of study for my major                                                              int64
The program of study for my major was well integrated.                                                                                              int64
Length: 134, dtype: object

In [114]:
# Calculate BMI
bmi = df['Weight (KG)  '] / ((df['Height (Feet)'] / 100) ** 2)

# Add BMI as a new column in the dataset
df['BMI'] = bmi

<ipython-input-114-8cbc4d30a54a>:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['BMI'] = bmi

In [115]:
df

,Gender,Area (Living),Age in years,Province,Weight (KG),Height (Feet),No. of siblings (Total number of sisters & Brothers),Your Highest Qualification,Family Occupation,Providing care to,...,I find teaching staff helpful when asked questions,I manage to complete the requirements of the program without feeling unduly stressed,The amount of work we are expected to do is quite reasonable.,I feel a strong sense of belonging to my class group,I frequently work together with others in my classes,I have frequently discussed ideas from courses with other students out-of-class,I have found that discussing course material with other students outside classes has helped me to reach a better understanding of the material,I can see how courses fitted together to make a coherent program of study for my major,The program of study for my major was well integrated.,BMI
0,0,0,18,0,55.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,inf
1,0,0,18,0,55.0,0,0,1,1,1,...,1,0,0,0,0,1,0,0,1,inf
2,0,0,18,0,55.0,0,0,2,1,1,...,0,0,0,1,1,2,0,0,1,inf
3,1,0,18,0,55.0,1,0,1,0,2,...,2,1,1,2,2,3,1,1,2,5.500000e+05
4,1,0,18,0,55.0,1,0,2,2,1,...,0,0,2,1,1,1,2,0,1,5.500000e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11396,0,1,80,0,100.0,86,6,1,0,3,...,1,0,0,0,2,4,3,2,0,1.352082e+02
11397,0,0,82,0,45.0,86,7,0,0,3,...,3,0,2,3,1,3,2,2,1,6.084370e+01
11398,0,0,85,0,54.0,86,7,1,0,2,...,1,2,3,0,3,2,0,2,0,7.301244e+01
11399,0,0,87,0,56.0,86,8,1,2,0,...,0,0,2,1,1,1,2,0,1,7.571660e+01
11400,1,0,43,5,64.0,86,6,1,2,2,...,0,3,3,1,1,1,2,0,1,8.653326e+01

In [116]:
df.isnull().any().any()  #This code tells you if you have some NaN value in you dataframe

False

In [117]:
df.isnull().any()

Gender                                                                                                                                            False
Area (Living)                                                                                                                                     False
Age in years                                                                                                                                      False
Province                                                                                                                                          False
Weight (KG)                                                                                                                                       False
                                                                                                                                                  ...
I have frequently discussed ideas from courses with other students out-of-class                                                                   False
I have found that discussing course material with other students outside classes has helped me to reach a better understanding of the material    False
I can see how courses fitted together to make a coherent program of study for my major                                                            False
The program of study for my major was well integrated.                                                                                            False
BMI                                                                                                                                               False
Length: 135, dtype: bool

In [118]:
import numpy as np
import pandas as pd

# Check for missing values
print(df.isnull().sum())

# Fill missing values with mean
df = df.fillna(df.mean())

# Check for infinite values
print(np.isinf(df).sum())

# Replace infinite values with NaN
df.replace([np.inf, -np.inf], np.nan, inplace=True)

# Fill NaN values with mean
df.fillna(df.mean(), inplace=True)

Gender                                                                                                                                            0
Area (Living)                                                                                                                                     0
Age in years                                                                                                                                      0
Province                                                                                                                                          0
Weight (KG)                                                                                                                                       0
                                                                                                                                                 ..
I have frequently discussed ideas from courses with other students out-of-class                                                                   0
I have found that discussing course material with other students outside classes has helped me to reach a better understanding of the material    0
I can see how courses fitted together to make a coherent program of study for my major                                                            0
The program of study for my major was well integrated.                                                                                            0
BMI                                                                                                                                               0
Length: 135, dtype: int64
Gender                                                                                                                                               0
Area (Living)                                                                                                                                        0
Age in years                                                                                                                                         0
Province                                                                                                                                             0
Weight (KG)                                                                                                                                          0
                                                                                                                                                  ...
I have frequently discussed ideas from courses with other students out-of-class                                                                      0
I have found that discussing course material with other students outside classes has helped me to reach a better understanding of the material       0
I can see how courses fitted together to make a coherent program of study for my major                                                               0
The program of study for my major was well integrated.                                                                                               0
BMI                                                                                                                                               1096
Length: 135, dtype: int64

In [131]:
from sklearn.model_selection import train_test_split

X = df.drop('Province', axis=1)
y = df.Province

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [132]:
print(np.isnan(y_train).any())
print(np.isinf(y_train).any())

False
False

In [133]:
X_train = X_train[~np.isnan(y_train) & ~np.isinf(y_train)]
y_train = y_train[~np.isnan(y_train) & ~np.isinf(y_train)]

In [134]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
        
    elif train==False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")        
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

# **LogisticRegression**

In [135]:
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression(solver='liblinear')
lr_clf.fit(X_train, y_train)

print_score(lr_clf, X_train, y_train, X_test, y_test, train=True)
print_score(lr_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:
================================================
Accuracy Score: 85.73%
_______________________________________________
CLASSIFICATION REPORT:
                     0           1           2           3           4  \
precision     0.858903    0.416667    0.500000    0.500000    0.125000
recall        0.998392    0.018248    0.008264    0.004065    0.003704
f1-score      0.923410    0.034965    0.016260    0.008065    0.007194
support    6841.000000  274.000000  121.000000  246.000000  270.000000

                    5     6  accuracy    macro avg  weighted avg
precision    0.750000   0.0  0.857268     0.450081      0.792785
recall       0.018868   0.0  0.857268     0.150220      0.857268
f1-score     0.036810   0.0  0.857268     0.146672      0.794282
support    159.000000  69.0  0.857268  7980.000000   7980.000000
_______________________________________________
Confusion Matrix:
 [[6830    5    0    0    5    1    0]
 [ 267    5    1    0    1    0    0]
 [ 119    0    1    0    1    0    0]
 [ 243    2    0    1    0    0    0]
 [ 268    0    0    1    1    0    0]
 [ 156    0    0    0    0    3    0]
 [  69    0    0    0    0    0    0]]

Test Result:
================================================
Accuracy Score: 85.47%
_______________________________________________
CLASSIFICATION REPORT:
                     0           1     2      3      4     5     6  accuracy  \
precision     0.857940    0.111111   0.0    0.0    0.0   0.0   0.0  0.854721
recall        0.997271    0.009434   0.0    0.0    0.0   0.0   0.0  0.854721
f1-score      0.922373    0.017391   0.0    0.0    0.0   0.0   0.0  0.854721
support    2931.000000  106.000000  48.0  117.0  114.0  74.0  31.0  0.854721

             macro avg  weighted avg
precision     0.138436      0.738497
recall        0.143815      0.854721
f1-score      0.134252      0.790798
support    3421.000000   3421.000000
_______________________________________________
Confusion Matrix:
 [[2923    5    0    0    1    2    0]
 [ 104    1    0    1    0    0    0]
 [  48    0    0    0    0    0    0]
 [ 117    0    0    0    0    0    0]
 [ 113    1    0    0    0    0    0]
 [  73    1    0    0    0    0    0]
 [  29    1    0    0    0    1    0]]

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [136]:
test_score = accuracy_score(y_test, lr_clf.predict(X_test)) * 100
train_score = accuracy_score(y_train, lr_clf.predict(X_train)) * 100

results_df = pd.DataFrame(data=[["Logistic Regression", train_score, test_score]], 
                          columns=['Model', 'Training Accuracy %', 'Testing Accuracy %'])
results_df

                 Model  Training Accuracy %  Testing Accuracy %
0  Logistic Regression            85.726817           85.472084

In [137]:
from sklearn.tree import DecisionTreeClassifier


tree_clf = DecisionTreeClassifier(random_state=42)
tree_clf.fit(X_train, y_train)

print_score(tree_clf, X_train, y_train, X_test, y_test, train=True)
print_score(tree_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:
================================================
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
                0      1      2      3      4      5     6  accuracy  \
precision     1.0    1.0    1.0    1.0    1.0    1.0   1.0       1.0
recall        1.0    1.0    1.0    1.0    1.0    1.0   1.0       1.0
f1-score      1.0    1.0    1.0    1.0    1.0    1.0   1.0       1.0
support    6841.0  274.0  121.0  246.0  270.0  159.0  69.0       1.0

           macro avg  weighted avg
precision        1.0           1.0
recall           1.0           1.0
f1-score         1.0           1.0
support       7980.0        7980.0
_______________________________________________
Confusion Matrix:
 [[6841    0    0    0    0    0    0]
 [   0  274    0    0    0    0    0]
 [   0    0  121    0    0    0    0]
 [   0    0    0  246    0    0    0]
 [   0    0    0    0  270    0    0]
 [   0    0    0    0    0  159    0]
 [   0    0    0    0    0    0   69]]

Test Result:
================================================
Accuracy Score: 73.19%
_______________________________________________
CLASSIFICATION REPORT:
                     0           1          2           3           4  \
precision     0.871867    0.067568   0.015873    0.048780    0.098592
recall        0.842716    0.094340   0.020833    0.051282    0.122807
f1-score      0.857044    0.078740   0.018018    0.050000    0.109375
support    2931.000000  106.000000  48.000000  117.000000  114.000000

                   5          6  accuracy    macro avg  weighted avg
precision   0.022727   0.041667   0.73195     0.166725      0.755126
recall      0.027027   0.032258   0.73195     0.170180      0.731950
f1-score    0.024691   0.036364   0.73195     0.167747      0.743198
support    74.000000  31.000000   0.73195  3421.000000   3421.000000
_______________________________________________
Confusion Matrix:
 [[2470  110   54  102  107   72   16]
 [  78   10    1    3    7    4    3]
 [  34    5    1    3    3    2    0]
 [  91    8    3    6    4    4    1]
 [  82    7    2    5   14    3    1]
 [  58    6    0    2    4    2    2]
 [  20    2    2    2    3    1    1]]

In [138]:
test_score = accuracy_score(y_test, tree_clf.predict(X_test)) * 100
train_score = accuracy_score(y_train, tree_clf.predict(X_train)) * 100

results_df_2 = pd.DataFrame(data=[["Decision Tree Classifier", train_score, test_score]], 
                          columns=['Model', 'Training Accuracy %', 'Testing Accuracy %'])
results_df = results_df.append(results_df_2, ignore_index=True)
results_df

<ipython-input-138-5ff1d90d217a>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results_df = results_df.append(results_df_2, ignore_index=True)

                      Model  Training Accuracy %  Testing Accuracy %
0       Logistic Regression            85.726817           85.472084
1  Decision Tree Classifier           100.000000           73.194972

In [139]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

rf_clf = RandomForestClassifier(n_estimators=1000, random_state=42)
rf_clf.fit(X_train, y_train)

print_score(rf_clf, X_train, y_train, X_test, y_test, train=True)
print_score(rf_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:
================================================
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
                0      1      2      3      4      5     6  accuracy  \
precision     1.0    1.0    1.0    1.0    1.0    1.0   1.0       1.0
recall        1.0    1.0    1.0    1.0    1.0    1.0   1.0       1.0
f1-score      1.0    1.0    1.0    1.0    1.0    1.0   1.0       1.0
support    6841.0  274.0  121.0  246.0  270.0  159.0  69.0       1.0

           macro avg  weighted avg
precision        1.0           1.0
recall           1.0           1.0
f1-score         1.0           1.0
support       7980.0        7980.0
_______________________________________________
Confusion Matrix:
 [[6841    0    0    0    0    0    0]
 [   0  274    0    0    0    0    0]
 [   0    0  121    0    0    0    0]
 [   0    0    0  246    0    0    0]
 [   0    0    0    0  270    0    0]
 [   0    0    0    0    0  159    0]
 [   0    0    0    0    0    0   69]]

Test Result:
================================================
Accuracy Score: 85.76%
_______________________________________________
CLASSIFICATION REPORT:
                     0      1     2      3           4     5          6  \
precision     0.857519    0.0   0.0    0.0    1.000000   0.0   1.000000
recall        1.000000    0.0   0.0    0.0    0.017544   0.0   0.032258
f1-score      0.923295    0.0   0.0    0.0    0.034483   0.0   0.062500
support    2931.000000  106.0  48.0  117.0  114.000000  74.0  31.000000

           accuracy    macro avg  weighted avg
precision  0.857644     0.408217      0.777079
recall     0.857644     0.149972      0.857644
f1-score   0.857644     0.145754      0.792764
support    0.857644  3421.000000   3421.000000
_______________________________________________
Confusion Matrix:
 [[2931    0    0    0    0    0    0]
 [ 106    0    0    0    0    0    0]
 [  48    0    0    0    0    0    0]
 [ 117    0    0    0    0    0    0]
 [ 112    0    0    0    2    0    0]
 [  74    0    0    0    0    0    0]
 [  30    0    0    0    0    0    1]]

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [140]:
test_score = accuracy_score(y_test, rf_clf.predict(X_test)) * 100
train_score = accuracy_score(y_train, rf_clf.predict(X_train)) * 100

results_df_2 = pd.DataFrame(data=[["Random Forest Classifier", train_score, test_score]], 
                          columns=['Model', 'Training Accuracy %', 'Testing Accuracy %'])
results_df = results_df.append(results_df_2, ignore_index=True)
results_df

<ipython-input-140-9dfba9c0999c>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results_df = results_df.append(results_df_2, ignore_index=True)

                      Model  Training Accuracy %  Testing Accuracy %
0       Logistic Regression            85.726817           85.472084
1  Decision Tree Classifier           100.000000           73.194972
2  Random Forest Classifier           100.000000           85.764396